### ISSUE TITLE
Configurations Secret Files

### ISSUE THREAD

**Issue by mario-oberwalder** [Gepardec/GranitTreff-030620#2]
I could have used some context for clarification:

docker/secrets/kubeConfig.txt is the one kind created above? is it already in base64 or do i need to do that? how do i make sure that just the intended configuration is included?

docker/secrets/nexusPassword.txt & docker/secrets/jenkinsAdminPassword.txt can be chosen freely since i set them later?

**Comment by cchet** [comment]
All secrets have to be provided during the setup and before the infrastructure is started. The Nexus password cannot be set automatically due to the fact that Nexus initializes its database and creates a default admin password during the initial start, which you have to change at the first login to the password you defined in the secret file. The secret files are used by Jenkins and not by Nexus.

The Kubernetes configuration is created by Docker Desktop for Windows or kind during the initial setup. It is plain text and you have to encode it into base64

`cat ~/.kube/config | base64 - > docker/secrets/kubeConfig.txt`

The Kubernetes configuration file is supposed to contain only the configuration for the cluster we want to use, otherwise Jenkins won't be able to determine which cluster to use. I will add an example in the docs.

**Comment by mario-oberwalder** [comment]
If i use `kubectl config view` i think i got some additional clusters in there already. Do I need to wipe the ~/.kube/config and start fresh?

**Comment by cchet** [comment]
No, you just need to copy paste it and clean it of all the configurations of the other clusters, so that only the intended one remains. See the example in doc/examples/kubeConfig.yml.

**Comment by cchet** [comment]
The Kubernetes Config you provide should be a copy of the original one because you need to encode in base64 anyway.
